=begin
#EVE Swagger Interface

#An OpenAPI for EVE Online

OpenAPI spec version: 0.8.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Esi::GetKillmailsKillmailIdKillmailHashItemsItem
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GetKillmailsKillmailIdKillmailHashItemsItem' do
  before do
    # run before each test
    @instance = Esi::GetKillmailsKillmailIdKillmailHashItemsItem.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GetKillmailsKillmailIdKillmailHashItemsItem' do
    it 'should create an instance of GetKillmailsKillmailIdKillmailHashItemsItem' do
      expect(@instance).to be_instance_of(Esi::GetKillmailsKillmailIdKillmailHashItemsItem)
    end
  end
  describe 'test attribute "flag"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "item_type_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "quantity_destroyed"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "quantity_dropped"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "singleton"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
