=begin
#EVE Swagger Interface

#An OpenAPI for EVE Online

OpenAPI spec version: 0.8.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Esi::PostCorporationsCorporationIdAssetsLocationsNotFound
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PostCorporationsCorporationIdAssetsLocationsNotFound' do
  before do
    # run before each test
    @instance = Esi::PostCorporationsCorporationIdAssetsLocationsNotFound.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PostCorporationsCorporationIdAssetsLocationsNotFound' do
    it 'should create an instance of PostCorporationsCorporationIdAssetsLocationsNotFound' do
      expect(@instance).to be_instance_of(Esi::PostCorporationsCorporationIdAssetsLocationsNotFound)
    end
  end
  describe 'test attribute "error"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
